name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  test:
    name: Unit Tests shard ${{ matrix.shard }}/${{ matrix.total }}
    runs-on: ${{ matrix.os }}
    needs: [install-dependencies]

    strategy:
      matrix:
        node-version: [20.16.0]
        os: [ubuntu-latest]
        shard: [0, 1]
        total: [2]
      fail-fast: false

    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Europe/Madrid
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      # run tests in parallel - https://vitest.dev/guide/cli.html#shard
      - name: Run Unit Tests Shard
        run: |
          pnpm test --shard `expr ${{ matrix.shard }} + 1`/${{ matrix.total }}
